apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.name }}
stringData:
  password: {{ .Values.vmware.password }}
  username: {{ .Values.vmware.username }}
