vmware:
  vcenter: 192.168.1.102
  thumbprint: D5:82:6E:52:6E:69:F3:C8:B6:7F:E9:CA:20:06:A8:B6:A1:70:97:0E
  datacenter: LAB01-DC
  datastore: LAB01-VSAN
  password: P@ssw0rd
  username: svc-capv@vsphere.local
  template: ubuntu-2004-kube-v1.21.2+vmware.1
  portgroup: capv-net
  resourcepool: capv-rp
  folder: CAPV
  memorymib: 4096
  numcpus: 2
  storagepolicyname: "vSAN Default Storage Policy"
  diskgib: 25

ssh:
  user: xavier
  pubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvKYb6bE+V2QXgOQKPbaL9ya8PKEc8YJBdfubajYz/ttHGiSVfQkP/qwRsGybp2w5wsxeBoaG7PlYaN5q6ZGS3T2CZZqTx/M/Ww3Sy3zvfMJWyzXRS/JQkQ2+kdBFDfWN7PuWytJUU6HjDqWDetfOGAnGJBoucRPIpY4kBK4iomRMw6/CZzzsAJGx3//2pUDqGbrHCBhrhga/giRplskR/Skr9bi/aG++GgS2hB/r2iJM+1cyFxpbtcoiH/L/WIAFUKXbANJO/2dh/LvwoETsXOKXSg+LLqoRuCZt+WzVt971pcyn00cOyvaxxBMnOki49mVsGEZPtsZvdc5oxbWEl9auVw2CDgOlSh6NUzm54aC/sS+RalWxO7+qR5kehA8yfKKf9KMPUlI5HPpa4+DBWdVC58YbVhAqANOGz1z1P1KmUbebarMjJVox3jw3bocjy4H0mPBwBI5O7PEV+aRPNRUzXghbbuqI2m4+ivmiPLtEm2xwI9bNOOcv5HZOXWjE=

cluster:
  name: default
  cidrblocks: 172.32.0.0/16
  vip: 192.168.1.145

controllers:
  replicas: 1

workers:
  replicas: 1
